const std = @import("std");
const backends = @import("backends/backends.zig");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const backend = b.option(
        backends.Backend,
        "backend",
        "Select the WebGPU backend to use",
    ) orelse .none;
    const skip_build = b.option(bool, "skip_build", "Skips everything in the build step. other than the webgpu module") orelse false;
    if (skip_build) return;

    const bindings_gen = BindingsGen.init(b);

    const webgpu_mod = b.addModule("webgpu", .{
        // Generated by `zig build gen`
        .root_source_file = b.path("src/bindings.zig"),
        .target = target,
        .optimize = optimize,
    });
    backends.link(@This(), b, webgpu_mod, backend, target, optimize);

    const docs_step = b.step("docs", "Generate docs");
    const docs_lib = b.addLibrary(.{
        .name = "webgpu-docs",
        .root_module = webgpu_mod,
    });
    docs_step.dependOn(&b.addInstallDirectory(.{
        .source_dir = docs_lib.getEmittedDocs(),
        .install_subdir = "docs",
        .install_dir = .prefix,
    }).step);

    const check_step = b.step("check", "Build everything without running tests");
    const test_step = b.step("test", "Run all tests");
    const enable_abi_tests = backend != .none;
    const test_bindings_file = bindings_gen.generateBindings(true);
    const webgpu_h_mod = b.addTranslateC(.{
        .root_source_file = bindings_gen.upstream.path("webgpu.h"),
        .target = target,
        .optimize = optimize,
    }).createModule();
    const test_helpers_mod = b.createModule(.{
        .root_source_file = b.path("src/test_helpers.zig"),
        .target = target,
        .optimize = optimize,
    });
    inline for ([_]?struct { []const u8, std.Build.LazyPath }{
        .{ "gen-unit-tests", b.path("tools/gen/tests.zig") },
        .{ "prelude", b.path("src/prelude_test.zig") },
        if (enable_abi_tests) .{ "webgpu", test_bindings_file } else null,
    }) |maybe_test_file| {
        if (maybe_test_file) |test_file| {
            const test_exe = b.addTest(.{
                .name = test_file.@"0",
                .root_module = b.createModule(.{
                    .root_source_file = test_file.@"1",
                    .target = target,
                    .optimize = optimize,
                    .imports = &.{
                        .{ .name = "c", .module = webgpu_h_mod },
                        .{ .name = "test_helpers", .module = test_helpers_mod },
                    },
                }),
                .use_llvm = true, // TODO: remove once the native backend is fixed
            });
            backends.link(@This(), b, test_exe.root_module, backend, target, optimize);
            if (backend == .wgpu_native and target.result.os.tag == .windows) {
                test_exe.bundle_compiler_rt = false;
            }

            check_step.dependOn(&test_exe.step);

            const run_test_exe = b.addRunArtifact(test_exe);
            test_step.dependOn(&run_test_exe.step);
        }
    }

    const gen_step = b.step("gen", "Generate bindings to src/bindings.zig");
    const usf = b.addUpdateSourceFiles();
    usf.addCopyFileToSource(
        bindings_gen.generateBindings(false),
        "src/bindings.zig",
    );
    // test first and only then gen. gen should fail if test fails
    usf.step.dependOn(test_step);
    gen_step.dependOn(&usf.step);
}

pub const BuildOptions = struct {
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    backend: Backend = .none,

    pub const Backend = backends.Backend;
};
pub fn buildWebgpu(b: *std.Build, options: BuildOptions) *std.Build.Module {
    const self = b.dependencyFromBuildZig(@This(), .{
        .skip_build = true,
    });
    const gen = BindingsGen.init(self.builder);
    const bindings_file = gen.generateBindings(false);
    const webgpu_mod = self.builder.createModule(.{
        .root_source_file = bindings_file,
        .target = options.target,
        .optimize = options.optimize,
    });
    backends.link(@This(), self.builder, webgpu_mod, options.backend, options.target, options.optimize);
    return webgpu_mod;
}

const BindingsGen = struct {
    b: *std.Build,
    upstream: *std.Build.Dependency,
    webgpu_json: std.Build.LazyPath,
    bindings_generator: *std.Build.Step.Compile,

    pub fn init(b: *std.Build) BindingsGen {
        const upstream = b.dependency("webgpu-headers-upstream", .{});
        const webgpu_json = upstream.path("webgpu.json");

        const bindings_generator = b.addExecutable(.{
            .name = "gen-bindings",
            .root_module = b.createModule(.{
                .root_source_file = b.path("tools/gen/main.zig"),
                .target = b.graph.host,
                .optimize = .Debug,
            }),
        });

        return .{
            .b = b,
            .upstream = upstream,
            .webgpu_json = webgpu_json,
            .bindings_generator = bindings_generator,
        };
    }

    pub fn generateBindings(
        self: *const BindingsGen,
        enable_abi_tests: bool,
    ) std.Build.LazyPath {
        const b = self.b;
        const run_bindings_generator = b.addRunArtifact(self.bindings_generator);
        run_bindings_generator.has_side_effects = true;
        if (enable_abi_tests) run_bindings_generator.addArg("--abi-checks");
        run_bindings_generator.addFileArg(self.webgpu_json);
        const bindings_file = run_bindings_generator.addOutputFileArg("bindings.zig");
        run_bindings_generator.addFileArg(b.path("src/prelude.zig"));

        return bindings_file;
    }
};
